gpu: 'cuda'
# gpu: 'cpu'
epochs: 200
optimizer: "adamw"
lr: 5e-5
min_lr: 1e-7
weight_decay: 0.01
warmup_epochs: 10
patience_epochs: 0
load_model: "./ckpt"
resume_from_checkpoint: False
log_every_n_steps: 50
fold_num: 5
LLRD: False
freeze_epoch: 0

model:
  # Bert
  max_position_embeddings: 128
  num_attention_heads: 12
  num_hidden_layers: 12
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  dropout: 0.1
  num_layers: 1

dataset:  
  # dataset_name: 'matbench_log_gvrh'
  # dataset_name: 'matbench_mp_e_form'
  # dataset_name: 'data/cond/slices'
  # dataset_name: 'matbench_jdft2d'
  # dataset_name: 'matbench_phonons'
  # dataset_name: 'matbench_dielectric'
  # dataset_name: 'matbench_log_kvrh'
  dataset_name: 'matbench_perovskites'
  # dataset_name: 'matbench_mp_gap'
  # dataset_name: './data/cond/gen'
  # dataset_name: 'unconvbench_defected'
  batch_size: 256
  num_workers: 2
  vocab_path: './tokenizer_cloud_optimade'
  blocksize: 128
  use_phys_params: true
  map_path: './data/mb_cloud.json'
  seed: 0
  valid_size: 0.25